FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Instalar dependencias
RUN npm ci --no-audit --no-fund

COPY . .

# ARG para la URL de la API durante build time
ARG VITE_API_URL=http://localhost:5000
ENV VITE_API_URL=$VITE_API_URL

EXPOSE 5173

# Modo desarrollo con hot reload
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]