version: "3.9"
services:
  db:
    build: ./db
    container_name: todo-db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: todo-backend
    environment:
      - DB_HOST=db
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_NAME=todos
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "3000:5173"

volumes:
  db_data:
