apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: frontend
          image: smenaq/todo-frontend:2.1
          ports:
            - containerPort: 5173
          env:
            - name: BACKEND_URL
              value: "http://todo-backend:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  type: NodePort
  ports:
    - port: 5173
      targetPort: 5173
      nodePort: 30080
  selector:
    app: todo-frontend
